### ISSUE TITLE
SciPy Talk Milestones

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium_web#11]
- [ ] Tooltips / documentation / info
- [x] Verify data management / upload
  - [x] Empty file
  - [x] Improperly formatted header
  - [x] Invalid zipfile
  - [x] Mismatched header/zipfile
- [x] Project / login info in sidebar (move from top)
- [x] Data tab
  - [ ] ~~Transformations (train/test split)~~
- [x] Features tab
  - [x] List in-progress tasks
  - [x] Organize features tab
    - [x] Separate out Lomb Scargle features
  - [ ] ~~Custom features upload~~
- [x] Models tab
  - [ ] ~~Models tab hyperparameter optimization~~
- [x] Predict tab
  - [x] Display prediction results
  - [ ] Export as CSV
- [x] Demo Docker container
- [x] Plots
- [x] Display notification for successful / failed tasks
- [x] Look into similar open source projects
- [ ] Miscellaneous UI fixes
  - [x] Update project should create when no projects exist (@stefanv)
  - [x] Remove Debug columns
  - [x] Add Dataset Delete, fix Featureset Delete
  - [x] Add Finished column (already stored as `model.finished`), or some kind of In Progress label
  - [ ] Allow prediction from featureset (w/o recomputing)

**Comment by bnaul** [comment]
Moving remaining items into separate issues.
